project:
  type: website
  output-dir: docs
  resources:
    - _img

website:
  title: "bucket"
  navbar:
    left:
      - href: index.qmd
        text: home
      - books.qmd
      - href: bookstats.qmd
        text: book stats
      - href: music.qmd
        text: music
      - about.qmd


format:
  html:
    theme:
      - morph
      # - sketchy
    css: styles.css
    toc: true



